/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IPyraMarket {
  export type ShareInfoStruct = {
    share: string;
    revenuePool: string;
    feePoint: BigNumberish;
    totalValue: BigNumberish;
  };

  export type ShareInfoStructOutput = [string, string, BigNumber, BigNumber] & {
    share: string;
    revenuePool: string;
    feePoint: BigNumber;
    totalValue: BigNumber;
  };
}

export interface PyraMarketInterface extends utils.Interface {
  functions: {
    "BASE_FEE_POINT()": FunctionFragment;
    "CREATOR_PREMINT()": FunctionFragment;
    "PROTOCOL_FEE_POINT()": FunctionFragment;
    "PROTOCOL_TREASURY()": FunctionFragment;
    "buyShares(address,uint256)": FunctionFragment;
    "createShare(string,string,uint256)": FunctionFragment;
    "emitRewardsClaimed(address,uint256)": FunctionFragment;
    "emitRewardsDistributed(address,uint256,uint256)": FunctionFragment;
    "emitSharesStaked(address,uint256)": FunctionFragment;
    "emitSharesUnstaked(address,uint256)": FunctionFragment;
    "getBuyPrice(address,uint256)": FunctionFragment;
    "getBuyPriceAfterFee(address,uint256)": FunctionFragment;
    "getPrice(uint256,uint256)": FunctionFragment;
    "getSellPrice(address,uint256)": FunctionFragment;
    "getSellPriceAfterFee(address,uint256)": FunctionFragment;
    "getShareInfo(address)": FunctionFragment;
    "sellShares(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BASE_FEE_POINT"
      | "CREATOR_PREMINT"
      | "PROTOCOL_FEE_POINT"
      | "PROTOCOL_TREASURY"
      | "buyShares"
      | "createShare"
      | "emitRewardsClaimed"
      | "emitRewardsDistributed"
      | "emitSharesStaked"
      | "emitSharesUnstaked"
      | "getBuyPrice"
      | "getBuyPriceAfterFee"
      | "getPrice"
      | "getSellPrice"
      | "getSellPriceAfterFee"
      | "getShareInfo"
      | "sellShares"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BASE_FEE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATOR_PREMINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_TREASURY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyShares",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createShare",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitRewardsClaimed",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitRewardsDistributed",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitSharesStaked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitSharesUnstaked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPriceAfterFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPriceAfterFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShareInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sellShares",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_FEE_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_PREMINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_TREASURY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitRewardsClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitSharesStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitSharesUnstaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShareInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellShares", data: BytesLike): Result;

  events: {
    "RewardsClaimed(address,address,address,uint256)": EventFragment;
    "RewardsDistributed(address,address,address,uint256,uint256)": EventFragment;
    "ShareCreated(address,address,address,string,string,uint256)": EventFragment;
    "SharesBought(address,address,uint256,uint256,uint256)": EventFragment;
    "SharesSold(address,address,uint256,uint256,uint256)": EventFragment;
    "SharesStaked(address,address,address,uint256)": EventFragment;
    "SharesUnstaked(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RewardsClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardsDistributed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShareCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesSold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesStaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesUnstaked"): EventFragment;
}

export interface RewardsClaimedEventObject {
  creator: string;
  share: string;
  shareholder: string;
  rewardsAmount: BigNumber;
}
export type RewardsClaimedEvent = TypedEvent<
  [string, string, string, BigNumber],
  RewardsClaimedEventObject
>;

export type RewardsClaimedEventFilter = TypedEventFilter<RewardsClaimedEvent>;

export interface RewardsDistributedEventObject {
  creator: string;
  share: string;
  shareholder: string;
  rewardsAmount: BigNumber;
  revenue: BigNumber;
}
export type RewardsDistributedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  RewardsDistributedEventObject
>;

export type RewardsDistributedEventFilter =
  TypedEventFilter<RewardsDistributedEvent>;

export interface ShareCreatedEventObject {
  creator: string;
  share: string;
  revenuePool: string;
  shareName: string;
  shareSymbol: string;
  feePoint: BigNumber;
}
export type ShareCreatedEvent = TypedEvent<
  [string, string, string, string, string, BigNumber],
  ShareCreatedEventObject
>;

export type ShareCreatedEventFilter = TypedEventFilter<ShareCreatedEvent>;

export interface SharesBoughtEventObject {
  creator: string;
  trader: string;
  buyAt: BigNumber;
  amount: BigNumber;
  price: BigNumber;
}
export type SharesBoughtEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  SharesBoughtEventObject
>;

export type SharesBoughtEventFilter = TypedEventFilter<SharesBoughtEvent>;

export interface SharesSoldEventObject {
  creator: string;
  trader: string;
  sellAt: BigNumber;
  amount: BigNumber;
  price: BigNumber;
}
export type SharesSoldEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  SharesSoldEventObject
>;

export type SharesSoldEventFilter = TypedEventFilter<SharesSoldEvent>;

export interface SharesStakedEventObject {
  creator: string;
  share: string;
  shareholder: string;
  sharesAmount: BigNumber;
}
export type SharesStakedEvent = TypedEvent<
  [string, string, string, BigNumber],
  SharesStakedEventObject
>;

export type SharesStakedEventFilter = TypedEventFilter<SharesStakedEvent>;

export interface SharesUnstakedEventObject {
  creator: string;
  share: string;
  shareholder: string;
  sharesAmount: BigNumber;
}
export type SharesUnstakedEvent = TypedEvent<
  [string, string, string, BigNumber],
  SharesUnstakedEventObject
>;

export type SharesUnstakedEventFilter = TypedEventFilter<SharesUnstakedEvent>;

export interface PyraMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PyraMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROTOCOL_TREASURY(overrides?: CallOverrides): Promise<[string]>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    createShare(
      shareName: string,
      shareSymbol: string,
      feePoint: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitRewardsClaimed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitRewardsDistributed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      revenueAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBuyPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBuyPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSellPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSellPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<[IPyraMarket.ShareInfoStructOutput]>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  BASE_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

  CREATOR_PREMINT(overrides?: CallOverrides): Promise<BigNumber>;

  PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

  PROTOCOL_TREASURY(overrides?: CallOverrides): Promise<string>;

  buyShares(
    creator: string,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  createShare(
    shareName: string,
    shareSymbol: string,
    feePoint: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitRewardsClaimed(
    shareholder: string,
    rewardsAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitRewardsDistributed(
    shareholder: string,
    rewardsAmount: BigNumberish,
    revenueAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitSharesStaked(
    shareholder: string,
    sharesAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitSharesUnstaked(
    shareholder: string,
    sharesAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBuyPrice(
    person: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBuyPriceAfterFee(
    person: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPrice(
    supply: BigNumberish,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSellPrice(
    person: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSellPriceAfterFee(
    person: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getShareInfo(
    creator: string,
    overrides?: CallOverrides
  ): Promise<IPyraMarket.ShareInfoStructOutput>;

  sellShares(
    creator: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_TREASURY(overrides?: CallOverrides): Promise<string>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createShare(
      shareName: string,
      shareSymbol: string,
      feePoint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitRewardsClaimed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitRewardsDistributed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      revenueAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBuyPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBuyPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<IPyraMarket.ShareInfoStructOutput>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RewardsClaimed(address,address,address,uint256)"(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      rewardsAmount?: null
    ): RewardsClaimedEventFilter;
    RewardsClaimed(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      rewardsAmount?: null
    ): RewardsClaimedEventFilter;

    "RewardsDistributed(address,address,address,uint256,uint256)"(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      rewardsAmount?: null,
      revenue?: null
    ): RewardsDistributedEventFilter;
    RewardsDistributed(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      rewardsAmount?: null,
      revenue?: null
    ): RewardsDistributedEventFilter;

    "ShareCreated(address,address,address,string,string,uint256)"(
      creator?: string | null,
      share?: string | null,
      revenuePool?: string | null,
      shareName?: null,
      shareSymbol?: null,
      feePoint?: null
    ): ShareCreatedEventFilter;
    ShareCreated(
      creator?: string | null,
      share?: string | null,
      revenuePool?: string | null,
      shareName?: null,
      shareSymbol?: null,
      feePoint?: null
    ): ShareCreatedEventFilter;

    "SharesBought(address,address,uint256,uint256,uint256)"(
      creator?: string | null,
      trader?: string | null,
      buyAt?: null,
      amount?: null,
      price?: null
    ): SharesBoughtEventFilter;
    SharesBought(
      creator?: string | null,
      trader?: string | null,
      buyAt?: null,
      amount?: null,
      price?: null
    ): SharesBoughtEventFilter;

    "SharesSold(address,address,uint256,uint256,uint256)"(
      creator?: string | null,
      trader?: string | null,
      sellAt?: null,
      amount?: null,
      price?: null
    ): SharesSoldEventFilter;
    SharesSold(
      creator?: string | null,
      trader?: string | null,
      sellAt?: null,
      amount?: null,
      price?: null
    ): SharesSoldEventFilter;

    "SharesStaked(address,address,address,uint256)"(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      sharesAmount?: null
    ): SharesStakedEventFilter;
    SharesStaked(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      sharesAmount?: null
    ): SharesStakedEventFilter;

    "SharesUnstaked(address,address,address,uint256)"(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      sharesAmount?: null
    ): SharesUnstakedEventFilter;
    SharesUnstaked(
      creator?: string | null,
      share?: string | null,
      shareholder?: string | null,
      sharesAmount?: null
    ): SharesUnstakedEventFilter;
  };

  estimateGas: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_TREASURY(overrides?: CallOverrides): Promise<BigNumber>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    createShare(
      shareName: string,
      shareSymbol: string,
      feePoint: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitRewardsClaimed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitRewardsDistributed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      revenueAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBuyPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBuyPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROTOCOL_FEE_POINT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PROTOCOL_TREASURY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createShare(
      shareName: string,
      shareSymbol: string,
      feePoint: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitRewardsClaimed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitRewardsDistributed(
      shareholder: string,
      rewardsAmount: BigNumberish,
      revenueAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBuyPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBuyPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSellPrice(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSellPriceAfterFee(
      person: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
