/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IPyraMarket {
  export type ShareInfoStruct = {
    share: string;
    revenuePool: string;
    totalValue: BigNumberish;
  };

  export type ShareInfoStructOutput = [string, string, BigNumber] & {
    share: string;
    revenuePool: string;
    totalValue: BigNumber;
  };
}

export interface PyraMarketInterface extends utils.Interface {
  functions: {
    "BASE_FEE_POINT()": FunctionFragment;
    "CREATOR_FEE_POINT()": FunctionFragment;
    "CREATOR_PREMINT()": FunctionFragment;
    "PROTOCOL_FEE_POINT()": FunctionFragment;
    "REVENUE_POOL_FEE_POINT()": FunctionFragment;
    "UPGRADE_INTERFACE_VERSION()": FunctionFragment;
    "buyAndStakeShares(address,uint256)": FunctionFragment;
    "buyShares(address,uint256)": FunctionFragment;
    "createShare(string,string)": FunctionFragment;
    "emitRevenueClaimed(address,uint256)": FunctionFragment;
    "emitSharesStaked(address,uint256)": FunctionFragment;
    "emitSharesUnstaked(address,uint256)": FunctionFragment;
    "getBuyPrice(address,uint256)": FunctionFragment;
    "getBuyPriceAfterFee(address,uint256)": FunctionFragment;
    "getPrice(uint256,uint256)": FunctionFragment;
    "getSellPrice(address,uint256)": FunctionFragment;
    "getSellPriceAfterFee(address,uint256)": FunctionFragment;
    "getShareInfo(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "protocolOwner()": FunctionFragment;
    "protocolTreasury()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "sellShares(address,uint256)": FunctionFragment;
    "setProtocolOwner(address)": FunctionFragment;
    "setProtocolTreasury(address)": FunctionFragment;
    "unstakeAndSellShares(address,uint256)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BASE_FEE_POINT"
      | "CREATOR_FEE_POINT"
      | "CREATOR_PREMINT"
      | "PROTOCOL_FEE_POINT"
      | "REVENUE_POOL_FEE_POINT"
      | "UPGRADE_INTERFACE_VERSION"
      | "buyAndStakeShares"
      | "buyShares"
      | "createShare"
      | "emitRevenueClaimed"
      | "emitSharesStaked"
      | "emitSharesUnstaked"
      | "getBuyPrice"
      | "getBuyPriceAfterFee"
      | "getPrice"
      | "getSellPrice"
      | "getSellPriceAfterFee"
      | "getShareInfo"
      | "initialize"
      | "protocolOwner"
      | "protocolTreasury"
      | "proxiableUUID"
      | "sellShares"
      | "setProtocolOwner"
      | "setProtocolTreasury"
      | "unstakeAndSellShares"
      | "upgradeToAndCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BASE_FEE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATOR_FEE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATOR_PREMINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVENUE_POOL_FEE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyAndStakeShares",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyShares",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createShare",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitRevenueClaimed",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitSharesStaked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitSharesUnstaked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPriceAfterFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPriceAfterFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShareInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellShares",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeAndSellShares",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_FEE_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_FEE_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_PREMINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVENUE_POOL_FEE_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyAndStakeShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitRevenueClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitSharesStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitSharesUnstaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShareInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeAndSellShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint64)": EventFragment;
    "ProtocolOwnerSet(address)": EventFragment;
    "ProtocolTreasurySet(address)": EventFragment;
    "RevenueClaimed(address,address,uint256,uint256)": EventFragment;
    "ShareCreated(address,address,address,string,string)": EventFragment;
    "SharesBought(address,address,uint256,uint256,uint256)": EventFragment;
    "SharesSold(address,address,uint256,uint256,uint256)": EventFragment;
    "SharesStaked(address,address,uint256,uint256)": EventFragment;
    "SharesUnstaked(address,address,uint256,uint256)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolOwnerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolTreasurySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevenueClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShareCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesSold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesStaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SharesUnstaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ProtocolOwnerSetEventObject {
  owner: string;
}
export type ProtocolOwnerSetEvent = TypedEvent<
  [string],
  ProtocolOwnerSetEventObject
>;

export type ProtocolOwnerSetEventFilter =
  TypedEventFilter<ProtocolOwnerSetEvent>;

export interface ProtocolTreasurySetEventObject {
  treasury: string;
}
export type ProtocolTreasurySetEvent = TypedEvent<
  [string],
  ProtocolTreasurySetEventObject
>;

export type ProtocolTreasurySetEventFilter =
  TypedEventFilter<ProtocolTreasurySetEvent>;

export interface RevenueClaimedEventObject {
  creator: string;
  shareholder: string;
  claimAt: BigNumber;
  revenue: BigNumber;
}
export type RevenueClaimedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  RevenueClaimedEventObject
>;

export type RevenueClaimedEventFilter = TypedEventFilter<RevenueClaimedEvent>;

export interface ShareCreatedEventObject {
  creator: string;
  share: string;
  revenuePool: string;
  shareName: string;
  shareSymbol: string;
}
export type ShareCreatedEvent = TypedEvent<
  [string, string, string, string, string],
  ShareCreatedEventObject
>;

export type ShareCreatedEventFilter = TypedEventFilter<ShareCreatedEvent>;

export interface SharesBoughtEventObject {
  creator: string;
  trader: string;
  buyAt: BigNumber;
  amount: BigNumber;
  price: BigNumber;
}
export type SharesBoughtEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  SharesBoughtEventObject
>;

export type SharesBoughtEventFilter = TypedEventFilter<SharesBoughtEvent>;

export interface SharesSoldEventObject {
  creator: string;
  trader: string;
  sellAt: BigNumber;
  amount: BigNumber;
  price: BigNumber;
}
export type SharesSoldEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  SharesSoldEventObject
>;

export type SharesSoldEventFilter = TypedEventFilter<SharesSoldEvent>;

export interface SharesStakedEventObject {
  creator: string;
  shareholder: string;
  stakeAt: BigNumber;
  sharesAmount: BigNumber;
}
export type SharesStakedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  SharesStakedEventObject
>;

export type SharesStakedEventFilter = TypedEventFilter<SharesStakedEvent>;

export interface SharesUnstakedEventObject {
  creator: string;
  shareholder: string;
  unstakeAt: BigNumber;
  sharesAmount: BigNumber;
}
export type SharesUnstakedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  SharesUnstakedEventObject
>;

export type SharesUnstakedEventFilter = TypedEventFilter<SharesUnstakedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface PyraMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PyraMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    CREATOR_FEE_POINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    REVENUE_POOL_FEE_POINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    buyAndStakeShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    createShare(
      shareName: string,
      shareSymbol: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitRevenueClaimed(
      shareholder: string,
      revenue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBuyPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBuyPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSellPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSellPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<[IPyraMarket.ShareInfoStructOutput]>;

    initialize(
      protocolOwner_: string,
      protocolTreasury_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    protocolOwner(overrides?: CallOverrides): Promise<[string]>;

    protocolTreasury(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setProtocolOwner(
      protocolOwner_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setProtocolTreasury(
      protocolTreasury_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unstakeAndSellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  BASE_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

  CREATOR_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

  CREATOR_PREMINT(overrides?: CallOverrides): Promise<BigNumber>;

  PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

  REVENUE_POOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

  UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

  buyAndStakeShares(
    creator: string,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  buyShares(
    creator: string,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  createShare(
    shareName: string,
    shareSymbol: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitRevenueClaimed(
    shareholder: string,
    revenue: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitSharesStaked(
    shareholder: string,
    sharesAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitSharesUnstaked(
    shareholder: string,
    sharesAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBuyPrice(
    creator: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBuyPriceAfterFee(
    creator: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPrice(
    supply: BigNumberish,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSellPrice(
    creator: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSellPriceAfterFee(
    creator: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getShareInfo(
    creator: string,
    overrides?: CallOverrides
  ): Promise<IPyraMarket.ShareInfoStructOutput>;

  initialize(
    protocolOwner_: string,
    protocolTreasury_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  protocolOwner(overrides?: CallOverrides): Promise<string>;

  protocolTreasury(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  sellShares(
    creator: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setProtocolOwner(
    protocolOwner_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setProtocolTreasury(
    protocolTreasury_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unstakeAndSellShares(
    creator: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    CREATOR_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    REVENUE_POOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

    buyAndStakeShares(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createShare(
      shareName: string,
      shareSymbol: string,
      overrides?: CallOverrides
    ): Promise<void>;

    emitRevenueClaimed(
      shareholder: string,
      revenue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBuyPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBuyPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<IPyraMarket.ShareInfoStructOutput>;

    initialize(
      protocolOwner_: string,
      protocolTreasury_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    protocolOwner(overrides?: CallOverrides): Promise<string>;

    protocolTreasury(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolOwner(
      protocolOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolTreasury(
      protocolTreasury_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unstakeAndSellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "ProtocolOwnerSet(address)"(
      owner?: string | null
    ): ProtocolOwnerSetEventFilter;
    ProtocolOwnerSet(owner?: string | null): ProtocolOwnerSetEventFilter;

    "ProtocolTreasurySet(address)"(
      treasury?: string | null
    ): ProtocolTreasurySetEventFilter;
    ProtocolTreasurySet(
      treasury?: string | null
    ): ProtocolTreasurySetEventFilter;

    "RevenueClaimed(address,address,uint256,uint256)"(
      creator?: string | null,
      shareholder?: string | null,
      claimAt?: null,
      revenue?: null
    ): RevenueClaimedEventFilter;
    RevenueClaimed(
      creator?: string | null,
      shareholder?: string | null,
      claimAt?: null,
      revenue?: null
    ): RevenueClaimedEventFilter;

    "ShareCreated(address,address,address,string,string)"(
      creator?: string | null,
      share?: string | null,
      revenuePool?: string | null,
      shareName?: null,
      shareSymbol?: null
    ): ShareCreatedEventFilter;
    ShareCreated(
      creator?: string | null,
      share?: string | null,
      revenuePool?: string | null,
      shareName?: null,
      shareSymbol?: null
    ): ShareCreatedEventFilter;

    "SharesBought(address,address,uint256,uint256,uint256)"(
      creator?: string | null,
      trader?: string | null,
      buyAt?: null,
      amount?: null,
      price?: null
    ): SharesBoughtEventFilter;
    SharesBought(
      creator?: string | null,
      trader?: string | null,
      buyAt?: null,
      amount?: null,
      price?: null
    ): SharesBoughtEventFilter;

    "SharesSold(address,address,uint256,uint256,uint256)"(
      creator?: string | null,
      trader?: string | null,
      sellAt?: null,
      amount?: null,
      price?: null
    ): SharesSoldEventFilter;
    SharesSold(
      creator?: string | null,
      trader?: string | null,
      sellAt?: null,
      amount?: null,
      price?: null
    ): SharesSoldEventFilter;

    "SharesStaked(address,address,uint256,uint256)"(
      creator?: string | null,
      shareholder?: string | null,
      stakeAt?: null,
      sharesAmount?: null
    ): SharesStakedEventFilter;
    SharesStaked(
      creator?: string | null,
      shareholder?: string | null,
      stakeAt?: null,
      sharesAmount?: null
    ): SharesStakedEventFilter;

    "SharesUnstaked(address,address,uint256,uint256)"(
      creator?: string | null,
      shareholder?: string | null,
      unstakeAt?: null,
      sharesAmount?: null
    ): SharesUnstakedEventFilter;
    SharesUnstaked(
      creator?: string | null,
      shareholder?: string | null,
      unstakeAt?: null,
      sharesAmount?: null
    ): SharesUnstakedEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    CREATOR_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    REVENUE_POOL_FEE_POINT(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    buyAndStakeShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    createShare(
      shareName: string,
      shareSymbol: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitRevenueClaimed(
      shareholder: string,
      revenue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBuyPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBuyPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      protocolOwner_: string,
      protocolTreasury_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    protocolOwner(overrides?: CallOverrides): Promise<BigNumber>;

    protocolTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setProtocolOwner(
      protocolOwner_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setProtocolTreasury(
      protocolTreasury_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unstakeAndSellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BASE_FEE_POINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CREATOR_FEE_POINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CREATOR_PREMINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROTOCOL_FEE_POINT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REVENUE_POOL_FEE_POINT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UPGRADE_INTERFACE_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyAndStakeShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    buyShares(
      creator: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createShare(
      shareName: string,
      shareSymbol: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitRevenueClaimed(
      shareholder: string,
      revenue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitSharesStaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitSharesUnstaked(
      shareholder: string,
      sharesAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBuyPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBuyPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSellPrice(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSellPriceAfterFee(
      creator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getShareInfo(
      creator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      protocolOwner_: string,
      protocolTreasury_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    protocolOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setProtocolOwner(
      protocolOwner_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setProtocolTreasury(
      protocolTreasury_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unstakeAndSellShares(
      creator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
