/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IDataMonetizer {
  export type ActParamsStruct = {
    assetId: BytesLike;
    actions: string[];
    actionProcessDatas: BytesLike[];
  };

  export type ActParamsStructOutput = [string, string[], string[]] & {
    assetId: string;
    actions: string[];
    actionProcessDatas: string[];
  };

  export type EIP712SignatureStruct = {
    signer: string;
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
    deadline: BigNumberish;
  };

  export type EIP712SignatureStructOutput = [
    string,
    number,
    string,
    string,
    BigNumber
  ] & { signer: string; v: number; r: string; s: string; deadline: BigNumber };

  export type AddActionsParamsStruct = {
    assetId: BytesLike;
    actions: string[];
    actionInitDatas: BytesLike[];
  };

  export type AddActionsParamsStructOutput = [string, string[], string[]] & {
    assetId: string;
    actions: string[];
    actionInitDatas: string[];
  };

  export type AssetStruct = {
    data: BytesLike;
    publishAt: BigNumberish;
    publicationId: BigNumberish;
    actions: string[];
  };

  export type AssetStructOutput = [string, BigNumber, BigNumber, string[]] & {
    data: string;
    publishAt: BigNumber;
    publicationId: BigNumber;
    actions: string[];
  };

  export type PublishParamsStruct = {
    data: BytesLike;
    actions: string[];
    actionInitDatas: BytesLike[];
  };

  export type PublishParamsStructOutput = [string, string[], string[]] & {
    data: string;
    actions: string[];
    actionInitDatas: string[];
  };
}

export declare namespace IPyraZone {
  export type SkimStatusStruct = {
    balance: BigNumberish;
    lastSkimAt: BigNumberish;
  };

  export type SkimStatusStructOutput = [BigNumber, BigNumber] & {
    balance: BigNumber;
    lastSkimAt: BigNumber;
  };

  export type ZoneAssetStruct = {
    publishAt: BigNumberish;
    publicationId: BigNumberish;
    actions: string[];
    tierkeys: string[];
  };

  export type ZoneAssetStructOutput = [
    BigNumber,
    BigNumber,
    string[],
    string[]
  ] & {
    publishAt: BigNumber;
    publicationId: BigNumber;
    actions: string[];
    tierkeys: string[];
  };
}

export interface PyraZoneInterface extends utils.Interface {
  functions: {
    "PYRA_MARKET()": FunctionFragment;
    "TIERKEY_EXPIRATION()": FunctionFragment;
    "act((bytes32,address[],bytes[]))": FunctionFragment;
    "actWithSig((bytes32,address[],bytes[]),(address,uint8,bytes32,bytes32,uint256))": FunctionFragment;
    "addActions((bytes32,address[],bytes[]))": FunctionFragment;
    "addActionsWithSig((bytes32,address[],bytes[]),(address,uint8,bytes32,bytes32,uint256))": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "assetIdByPublisher(address)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "buyTierkey(bytes32,uint256)": FunctionFragment;
    "createTierkey(bytes32)": FunctionFragment;
    "eip712Domain()": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "getAsset(bytes32)": FunctionFragment;
    "getAssetOwner(bytes32)": FunctionFragment;
    "getDomainSeparator()": FunctionFragment;
    "getSigNonce(address)": FunctionFragment;
    "getSkimStatus(bytes32)": FunctionFragment;
    "getTierkeyPrice(bytes32,uint256,uint8)": FunctionFragment;
    "getTierkeyPriceAfterFee(bytes32,uint256,uint8)": FunctionFragment;
    "getZoneAsset(bytes32)": FunctionFragment;
    "isAccessible(bytes32,address,uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "isTierkeyExpired(bytes32,uint256,uint256)": FunctionFragment;
    "liquidateTierkey(bytes32,uint256,uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "publish((bytes,address[],bytes[]))": FunctionFragment;
    "publishWithSig((bytes,address[],bytes[]),(address,uint8,bytes32,bytes32,uint256))": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,bytes)": FunctionFragment;
    "sellTierkey(bytes32,uint256,uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "skim(bytes32)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "tokenByIndex(uint256)": FunctionFragment;
    "tokenOfOwnerByIndex(address,uint256)": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PYRA_MARKET"
      | "TIERKEY_EXPIRATION"
      | "act"
      | "actWithSig"
      | "addActions"
      | "addActionsWithSig"
      | "approve"
      | "assetIdByPublisher"
      | "balanceOf"
      | "buyTierkey"
      | "createTierkey"
      | "eip712Domain"
      | "getApproved"
      | "getAsset"
      | "getAssetOwner"
      | "getDomainSeparator"
      | "getSigNonce"
      | "getSkimStatus"
      | "getTierkeyPrice"
      | "getTierkeyPriceAfterFee"
      | "getZoneAsset"
      | "isAccessible"
      | "isApprovedForAll"
      | "isTierkeyExpired"
      | "liquidateTierkey"
      | "name"
      | "ownerOf"
      | "publish"
      | "publishWithSig"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "sellTierkey"
      | "setApprovalForAll"
      | "skim"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PYRA_MARKET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIERKEY_EXPIRATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "act",
    values: [IDataMonetizer.ActParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "actWithSig",
    values: [
      IDataMonetizer.ActParamsStruct,
      IDataMonetizer.EIP712SignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addActions",
    values: [IDataMonetizer.AddActionsParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addActionsWithSig",
    values: [
      IDataMonetizer.AddActionsParamsStruct,
      IDataMonetizer.EIP712SignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetIdByPublisher",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "buyTierkey",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTierkey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAsset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAssetOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getSigNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getSkimStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierkeyPrice",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierkeyPriceAfterFee",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getZoneAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccessible",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isTierkeyExpired",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateTierkey",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publish",
    values: [IDataMonetizer.PublishParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "publishWithSig",
    values: [
      IDataMonetizer.PublishParamsStruct,
      IDataMonetizer.EIP712SignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellTierkey",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "skim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PYRA_MARKET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIERKEY_EXPIRATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "act", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "actWithSig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addActions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addActionsWithSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetIdByPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTierkey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTierkey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSigNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkimStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierkeyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierkeyPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZoneAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAccessible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTierkeyExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateTierkey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "publish", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishWithSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellTierkey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "AssetActed(bytes32,address,uint256,address[],bytes[],bytes[])": EventFragment;
    "AssetActionsAdded(bytes32,address[],bytes[])": EventFragment;
    "AssetPublished(bytes32,address,uint256,uint256,bytes,address[],bytes[])": EventFragment;
    "EIP712DomainChanged()": EventFragment;
    "Skimed(bytes32,address,uint256,address,uint256)": EventFragment;
    "TierkeyBought(bytes32,uint256,uint256,uint256,address,uint256)": EventFragment;
    "TierkeyCreated(bytes32,uint256,address,uint256)": EventFragment;
    "TierkeyLiquidated(bytes32,uint256,uint256,uint256,address,uint256)": EventFragment;
    "TierkeySold(bytes32,uint256,uint256,uint256,address,uint256,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetActed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetActionsAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetPublished"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Skimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierkeyBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierkeyCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierkeyLiquidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierkeySold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  approved: string;
  tokenId: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface AssetActedEventObject {
  assetId: string;
  actor: string;
  actAt: BigNumber;
  actions: string[];
  actionProcessDatas: string[];
  actionReturnDatas: string[];
}
export type AssetActedEvent = TypedEvent<
  [string, string, BigNumber, string[], string[], string[]],
  AssetActedEventObject
>;

export type AssetActedEventFilter = TypedEventFilter<AssetActedEvent>;

export interface AssetActionsAddedEventObject {
  assetId: string;
  actions: string[];
  actionInitDatas: string[];
}
export type AssetActionsAddedEvent = TypedEvent<
  [string, string[], string[]],
  AssetActionsAddedEventObject
>;

export type AssetActionsAddedEventFilter =
  TypedEventFilter<AssetActionsAddedEvent>;

export interface AssetPublishedEventObject {
  assetId: string;
  publisher: string;
  publicationId: BigNumber;
  publishAt: BigNumber;
  data: string;
  actions: string[];
  actionInitDatas: string[];
}
export type AssetPublishedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, string[], string[]],
  AssetPublishedEventObject
>;

export type AssetPublishedEventFilter = TypedEventFilter<AssetPublishedEvent>;

export interface EIP712DomainChangedEventObject {}
export type EIP712DomainChangedEvent = TypedEvent<
  [],
  EIP712DomainChangedEventObject
>;

export type EIP712DomainChangedEventFilter =
  TypedEventFilter<EIP712DomainChangedEvent>;

export interface SkimedEventObject {
  assetId: string;
  revenuePool: string;
  skimAt: BigNumber;
  skimmer: string;
  skimAmount: BigNumber;
}
export type SkimedEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber],
  SkimedEventObject
>;

export type SkimedEventFilter = TypedEventFilter<SkimedEvent>;

export interface TierkeyBoughtEventObject {
  assetId: string;
  tier: BigNumber;
  keyId: BigNumber;
  buyAt: BigNumber;
  trader: string;
  keyPrice: BigNumber;
}
export type TierkeyBoughtEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string, BigNumber],
  TierkeyBoughtEventObject
>;

export type TierkeyBoughtEventFilter = TypedEventFilter<TierkeyBoughtEvent>;

export interface TierkeyCreatedEventObject {
  assetId: string;
  tier: BigNumber;
  tierkey: string;
  expiration: BigNumber;
}
export type TierkeyCreatedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  TierkeyCreatedEventObject
>;

export type TierkeyCreatedEventFilter = TypedEventFilter<TierkeyCreatedEvent>;

export interface TierkeyLiquidatedEventObject {
  assetId: string;
  tier: BigNumber;
  keyId: BigNumber;
  liquidateAt: BigNumber;
  liquidator: string;
  keyPrice: BigNumber;
}
export type TierkeyLiquidatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string, BigNumber],
  TierkeyLiquidatedEventObject
>;

export type TierkeyLiquidatedEventFilter =
  TypedEventFilter<TierkeyLiquidatedEvent>;

export interface TierkeySoldEventObject {
  assetId: string;
  tier: BigNumber;
  keyId: BigNumber;
  sellAt: BigNumber;
  trader: string;
  keyPrice: BigNumber;
  depreciatedKeyPrice: BigNumber;
}
export type TierkeySoldEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string, BigNumber, BigNumber],
  TierkeySoldEventObject
>;

export type TierkeySoldEventFilter = TypedEventFilter<TierkeySoldEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  tokenId: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface PyraZone extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PyraZoneInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PYRA_MARKET(overrides?: CallOverrides): Promise<[string]>;

    TIERKEY_EXPIRATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    act(
      actParams: IDataMonetizer.ActParamsStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    actWithSig(
      actParams: IDataMonetizer.ActParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    addActions(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addActionsWithSig(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    assetIdByPublisher(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    buyTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    createTierkey(
      assetId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[IDataMonetizer.AssetStructOutput]>;

    getAssetOwner(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDomainSeparator(overrides?: CallOverrides): Promise<[string]>;

    getSigNonce(
      signer: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSkimStatus(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[IPyraZone.SkimStatusStructOutput]>;

    getTierkeyPrice(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTierkeyPriceAfterFee(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getZoneAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[IPyraZone.ZoneAssetStructOutput]>;

    isAccessible(
      assetId: BytesLike,
      account: string,
      tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isTierkeyExpired(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    liquidateTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    publish(
      publishParams: IDataMonetizer.PublishParamsStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    publishWithSig(
      publishParams: IDataMonetizer.PublishParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sellTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    skim(
      assetId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferFrom(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  PYRA_MARKET(overrides?: CallOverrides): Promise<string>;

  TIERKEY_EXPIRATION(overrides?: CallOverrides): Promise<BigNumber>;

  act(
    actParams: IDataMonetizer.ActParamsStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  actWithSig(
    actParams: IDataMonetizer.ActParamsStruct,
    signature: IDataMonetizer.EIP712SignatureStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  addActions(
    addActionsParams: IDataMonetizer.AddActionsParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addActionsWithSig(
    addActionsParams: IDataMonetizer.AddActionsParamsStruct,
    signature: IDataMonetizer.EIP712SignatureStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  approve(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  assetIdByPublisher(arg0: string, overrides?: CallOverrides): Promise<string>;

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  buyTierkey(
    assetId: BytesLike,
    tier: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  createTierkey(
    assetId: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  eip712Domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  getApproved(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getAsset(
    assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<IDataMonetizer.AssetStructOutput>;

  getAssetOwner(assetId: BytesLike, overrides?: CallOverrides): Promise<string>;

  getDomainSeparator(overrides?: CallOverrides): Promise<string>;

  getSigNonce(signer: string, overrides?: CallOverrides): Promise<BigNumber>;

  getSkimStatus(
    assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<IPyraZone.SkimStatusStructOutput>;

  getTierkeyPrice(
    assetId: BytesLike,
    tier: BigNumberish,
    tradeType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTierkeyPriceAfterFee(
    assetId: BytesLike,
    tier: BigNumberish,
    tradeType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getZoneAsset(
    assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<IPyraZone.ZoneAssetStructOutput>;

  isAccessible(
    assetId: BytesLike,
    account: string,
    tier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isApprovedForAll(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isTierkeyExpired(
    assetId: BytesLike,
    tier: BigNumberish,
    keyId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  liquidateTierkey(
    assetId: BytesLike,
    tier: BigNumberish,
    keyId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  publish(
    publishParams: IDataMonetizer.PublishParamsStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  publishWithSig(
    publishParams: IDataMonetizer.PublishParamsStruct,
    signature: IDataMonetizer.EIP712SignatureStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sellTierkey(
    assetId: BytesLike,
    tier: BigNumberish,
    keyId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  skim(
    assetId: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  tokenByIndex(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenOfOwnerByIndex(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transferFrom(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    PYRA_MARKET(overrides?: CallOverrides): Promise<string>;

    TIERKEY_EXPIRATION(overrides?: CallOverrides): Promise<BigNumber>;

    act(
      actParams: IDataMonetizer.ActParamsStruct,
      overrides?: CallOverrides
    ): Promise<string[]>;

    actWithSig(
      actParams: IDataMonetizer.ActParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: CallOverrides
    ): Promise<string[]>;

    addActions(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addActionsWithSig(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    assetIdByPublisher(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createTierkey(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<IDataMonetizer.AssetStructOutput>;

    getAssetOwner(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getDomainSeparator(overrides?: CallOverrides): Promise<string>;

    getSigNonce(signer: string, overrides?: CallOverrides): Promise<BigNumber>;

    getSkimStatus(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<IPyraZone.SkimStatusStructOutput>;

    getTierkeyPrice(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTierkeyPriceAfterFee(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZoneAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<IPyraZone.ZoneAssetStructOutput>;

    isAccessible(
      assetId: BytesLike,
      account: string,
      tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isTierkeyExpired(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    liquidateTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    publish(
      publishParams: IDataMonetizer.PublishParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    publishWithSig(
      publishParams: IDataMonetizer.PublishParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    sellTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    skim(assetId: BytesLike, overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): ApprovalEventFilter;
    Approval(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "AssetActed(bytes32,address,uint256,address[],bytes[],bytes[])"(
      assetId?: BytesLike | null,
      actor?: string | null,
      actAt?: null,
      actions?: null,
      actionProcessDatas?: null,
      actionReturnDatas?: null
    ): AssetActedEventFilter;
    AssetActed(
      assetId?: BytesLike | null,
      actor?: string | null,
      actAt?: null,
      actions?: null,
      actionProcessDatas?: null,
      actionReturnDatas?: null
    ): AssetActedEventFilter;

    "AssetActionsAdded(bytes32,address[],bytes[])"(
      assetId?: BytesLike | null,
      actions?: null,
      actionInitDatas?: null
    ): AssetActionsAddedEventFilter;
    AssetActionsAdded(
      assetId?: BytesLike | null,
      actions?: null,
      actionInitDatas?: null
    ): AssetActionsAddedEventFilter;

    "AssetPublished(bytes32,address,uint256,uint256,bytes,address[],bytes[])"(
      assetId?: BytesLike | null,
      publisher?: string | null,
      publicationId?: BigNumberish | null,
      publishAt?: null,
      data?: null,
      actions?: null,
      actionInitDatas?: null
    ): AssetPublishedEventFilter;
    AssetPublished(
      assetId?: BytesLike | null,
      publisher?: string | null,
      publicationId?: BigNumberish | null,
      publishAt?: null,
      data?: null,
      actions?: null,
      actionInitDatas?: null
    ): AssetPublishedEventFilter;

    "EIP712DomainChanged()"(): EIP712DomainChangedEventFilter;
    EIP712DomainChanged(): EIP712DomainChangedEventFilter;

    "Skimed(bytes32,address,uint256,address,uint256)"(
      assetId?: BytesLike | null,
      revenuePool?: string | null,
      skimAt?: null,
      skimmer?: null,
      skimAmount?: null
    ): SkimedEventFilter;
    Skimed(
      assetId?: BytesLike | null,
      revenuePool?: string | null,
      skimAt?: null,
      skimmer?: null,
      skimAmount?: null
    ): SkimedEventFilter;

    "TierkeyBought(bytes32,uint256,uint256,uint256,address,uint256)"(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      keyId?: BigNumberish | null,
      buyAt?: null,
      trader?: null,
      keyPrice?: null
    ): TierkeyBoughtEventFilter;
    TierkeyBought(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      keyId?: BigNumberish | null,
      buyAt?: null,
      trader?: null,
      keyPrice?: null
    ): TierkeyBoughtEventFilter;

    "TierkeyCreated(bytes32,uint256,address,uint256)"(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      tierkey?: string | null,
      expiration?: null
    ): TierkeyCreatedEventFilter;
    TierkeyCreated(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      tierkey?: string | null,
      expiration?: null
    ): TierkeyCreatedEventFilter;

    "TierkeyLiquidated(bytes32,uint256,uint256,uint256,address,uint256)"(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      keyId?: BigNumberish | null,
      liquidateAt?: null,
      liquidator?: null,
      keyPrice?: null
    ): TierkeyLiquidatedEventFilter;
    TierkeyLiquidated(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      keyId?: BigNumberish | null,
      liquidateAt?: null,
      liquidator?: null,
      keyPrice?: null
    ): TierkeyLiquidatedEventFilter;

    "TierkeySold(bytes32,uint256,uint256,uint256,address,uint256,uint256)"(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      keyId?: BigNumberish | null,
      sellAt?: null,
      trader?: null,
      keyPrice?: null,
      depreciatedKeyPrice?: null
    ): TierkeySoldEventFilter;
    TierkeySold(
      assetId?: BytesLike | null,
      tier?: BigNumberish | null,
      keyId?: BigNumberish | null,
      sellAt?: null,
      trader?: null,
      keyPrice?: null,
      depreciatedKeyPrice?: null
    ): TierkeySoldEventFilter;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TransferEventFilter;
    Transfer(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TransferEventFilter;
  };

  estimateGas: {
    PYRA_MARKET(overrides?: CallOverrides): Promise<BigNumber>;

    TIERKEY_EXPIRATION(overrides?: CallOverrides): Promise<BigNumber>;

    act(
      actParams: IDataMonetizer.ActParamsStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    actWithSig(
      actParams: IDataMonetizer.ActParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    addActions(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addActionsWithSig(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    assetIdByPublisher(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    createTierkey(
      assetId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAsset(assetId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getAssetOwner(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDomainSeparator(overrides?: CallOverrides): Promise<BigNumber>;

    getSigNonce(signer: string, overrides?: CallOverrides): Promise<BigNumber>;

    getSkimStatus(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTierkeyPrice(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTierkeyPriceAfterFee(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZoneAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAccessible(
      assetId: BytesLike,
      account: string,
      tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isTierkeyExpired(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publish(
      publishParams: IDataMonetizer.PublishParamsStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    publishWithSig(
      publishParams: IDataMonetizer.PublishParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sellTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    skim(
      assetId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PYRA_MARKET(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TIERKEY_EXPIRATION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    act(
      actParams: IDataMonetizer.ActParamsStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    actWithSig(
      actParams: IDataMonetizer.ActParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addActions(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addActionsWithSig(
      addActionsParams: IDataMonetizer.AddActionsParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    assetIdByPublisher(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createTierkey(
      assetId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAssetOwner(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDomainSeparator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSigNonce(
      signer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSkimStatus(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTierkeyPrice(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTierkeyPriceAfterFee(
      assetId: BytesLike,
      tier: BigNumberish,
      tradeType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getZoneAsset(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAccessible(
      assetId: BytesLike,
      account: string,
      tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTierkeyExpired(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidateTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publish(
      publishParams: IDataMonetizer.PublishParamsStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    publishWithSig(
      publishParams: IDataMonetizer.PublishParamsStruct,
      signature: IDataMonetizer.EIP712SignatureStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sellTierkey(
      assetId: BytesLike,
      tier: BigNumberish,
      keyId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    skim(
      assetId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferFrom(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
